services:
  - type: web
    name: spotter-fuel-route-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ORS_API_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "true"
